### ISSUE TITLE
Error: TypeLoadException - Could not load type 'Umbraco.Core.UmbracoApplicationBase' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by eriktbe** [Shazwazza/UmbracoLinqPadDriver#7]
I'm getting the following error after trying to add a connection to my local Umbraco 8.9.1 instance:

Error: TypeLoadException - Could not load type 'Umbraco.Core.UmbracoApplicationBase' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by Shazwazza** [comment]
Sorry this project doesn't support v8. I never had time to port it.

**Comment by Shazwazza** [comment]
I'm not sure how much interest there is in making that happen. You are the first person to ask and v8 has been out for some time. If theres more interest than I thought, I can look into making some time to do it.
